apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: argo-application-jwt-auth
  namespace: argocd
spec:
  project: default
  source: 
    repoURL: "https://github.com/Shravankamble/argocd-project.git"
    targetRevision: HEAD
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: jwt-auth
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      - selfHeal: true
      - prune: true