apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ngrok-ingress-controller
  namespace: argocd
spec:
  project: default
  source:
    chart: kubernetes-ingress-controller
    repoURL: https://ngrok.github.io/kubernetes-ingress-controller
    targetRevision: 0.10.0
    helm:
      parameters:
      - name: "credentials.apiKey"
        value: # your ngrok apiKey goes here
      - name: "credentials.authtoken"
        value: # your ngrok authtoken goes here
  destination:
    server: "https://kubernetes.default.svc"
    namespace: ngrok-ingress-controller
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
